# Generated by Django 5.0.2 on 2024-02-19 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='active_contacts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
