# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: contacts.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63ontacts.proto\x12\x05users\"a\n\x07\x43ontact\x12\x14\n\x0c\x63ontact_uuid\x18\x01 \x01(\t\x12\x14\n\x0c\x63hannel_uuid\x18\x02 \x01(\t\x12\x14\n\x0cmessage_date\x18\x03 \x01(\t\x12\x14\n\x0cmessage_uuid\x18\x04 \x01(\t\"9\n\x15\x43reateContactsRequest\x12 \n\x08\x63ontacts\x18\x01 \x03(\x0b\x32\x0e.users.Contact\"\x18\n\x16\x43reateContactsResponse2Y\n\x08\x43ontacts\x12M\n\x0e\x43reateContacts\x12\x1c.users.CreateContactsRequest\x1a\x1d.users.CreateContactsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'contacts_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CONTACT']._serialized_start=25
  _globals['_CONTACT']._serialized_end=122
  _globals['_CREATECONTACTSREQUEST']._serialized_start=124
  _globals['_CREATECONTACTSREQUEST']._serialized_end=181
  _globals['_CREATECONTACTSRESPONSE']._serialized_start=183
  _globals['_CREATECONTACTSRESPONSE']._serialized_end=207
  _globals['_CONTACTS']._serialized_start=209
  _globals['_CONTACTS']._serialized_end=298
# @@protoc_insertion_point(module_scope)
