# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import contacts_pb2 as contacts__pb2


class ContactsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateContacts = channel.unary_unary(
                '/users.Contacts/CreateContacts',
                request_serializer=contacts__pb2.CreateContactsRequest.SerializeToString,
                response_deserializer=contacts__pb2.CreateContactsResponse.FromString,
                )


class ContactsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateContacts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ContactsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateContacts': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateContacts,
                    request_deserializer=contacts__pb2.CreateContactsRequest.FromString,
                    response_serializer=contacts__pb2.CreateContactsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'users.Contacts', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Contacts(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateContacts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/users.Contacts/CreateContacts',
            contacts__pb2.CreateContactsRequest.SerializeToString,
            contacts__pb2.CreateContactsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
