# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import message_pb2 as message__pb2


class FlowsMesssageStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateMessage = channel.unary_unary(
                '/message.FlowsMesssage/CreateMessage',
                request_serializer=message__pb2.CreateFlowsMessageRequest.SerializeToString,
                response_deserializer=message__pb2.CreateFlowsMessageResponse.FromString,
                )


class FlowsMesssageServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FlowsMesssageServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateMessage,
                    request_deserializer=message__pb2.CreateFlowsMessageRequest.FromString,
                    response_serializer=message__pb2.CreateFlowsMessageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'message.FlowsMesssage', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FlowsMesssage(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/message.FlowsMesssage/CreateMessage',
            message__pb2.CreateFlowsMessageRequest.SerializeToString,
            message__pb2.CreateFlowsMessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
