# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\x12\x07message\"s\n\x19\x43reateFlowsMessageRequest\x12\x14\n\x0c\x63ontact_uuid\x18\x01 \x01(\t\x12\x14\n\x0c\x63hannel_uuid\x18\x02 \x01(\t\x12\x14\n\x0cmessage_date\x18\x03 \x01(\t\x12\x14\n\x0cmessage_uuid\x18\x04 \x01(\t\"-\n\x1a\x43reateFlowsMessageResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2k\n\rFlowsMesssage\x12Z\n\rCreateMessage\x12\".message.CreateFlowsMessageRequest\x1a#.message.CreateFlowsMessageResponse\"\x00\x42)Z\'github.com/nyaruka/courier/grpc/billingb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\'github.com/nyaruka/courier/grpc/billing'
  _globals['_CREATEFLOWSMESSAGEREQUEST']._serialized_start=26
  _globals['_CREATEFLOWSMESSAGEREQUEST']._serialized_end=141
  _globals['_CREATEFLOWSMESSAGERESPONSE']._serialized_start=143
  _globals['_CREATEFLOWSMESSAGERESPONSE']._serialized_end=188
  _globals['_FLOWSMESSSAGE']._serialized_start=190
  _globals['_FLOWSMESSSAGE']._serialized_end=297
# @@protoc_insertion_point(module_scope)
